### ISSUE TITLE
Confusion?

### ISSUE THREAD

**Issue by DJSean00** [Samueleonard/AIG-ModelMatching-For-MSFS#1]
Do we download the large pack off the main Github page followed by the updated package under releases? and simply copy/paste/overwrite the main pack?

**Comment by Samueleonard** [comment]
Just download the google drive link and put that folder in your community folder, no need to touch the GitHub link, that’s just for my reference

**Comment by MoemenShahawy** [comment]
> Just download the google drive link and put that folder in your community folder, no need to touch the GitHub link, that’s just for my reference

So I just downloaded the github asset which is basically a 3.5gb folder after extraction
Looked in it and it seems that there isn't much missing, what's the difference between it and the 35gb google drive link? I mean it's 10x the size which would probably make the sim load much slower, would I be missing something by using the github download?

Goes without saying, you are doing the community and everyone a HUGE favor that can never be thanked enough :)

**Comment by Samueleonard** [comment]
Essentially the GitHub is missing all of the physical texture files (which makes up the vast majority of the 40gb) 

simply, the GitHub folder is useless on it’s own, the sim won’t have any textures to display, just blank models

I just use the GitHub repo as a way to track changes between updates, as I can see which important files have changed, without being bothered by 25000 texture changes
