### ISSUE TITLE
Pull request

### ISSUE THREAD

**Issue by Fifcok** [Samueleonard/AIG-ModelMatching-For-MSFS#10]
Is it possible to pull request only 1 folder from repo?

I mean aig-aitraffic-oci-beta from url

https://github.com/Samueleonard/AIG-ModelMatching-For-MSFS/tree/main/aig-aitraffic-oci-beta

In **githubdesktop** I need login and password, my account do not have privilages

**Comment by Fifcok** [comment]
![image](https://user-images.githubusercontent.com/105712834/170306619-d9f58636-5f58-4fcf-ac75-bfe86ecc1d23.png)

**Comment by Fifcok** [comment]
Maby you could change the topic to aig-aitraffic-oci-beta and then everything put into main topic

_The general way to do this is to put all the changes you want to on a topic branch and then to send a pull request for this branch._

**Comment by Fifcok** [comment]
![image](https://user-images.githubusercontent.com/105712834/170308329-6fa94256-29e1-4af4-80d6-f2d6049b2283.png)

**Comment by Fifcok** [comment]
Like this (edited screen)

![image](https://user-images.githubusercontent.com/105712834/170308435-8244e19d-955d-4f2a-b47e-e0050182d0b8.png)

It will be easier to pull request and have all the time everything updated

**Comment by Samueleonard** [comment]
sorry i'm not sure what you mean with your question.

you should not have to download anything from GitHub at any time.
The repo is there purely for my usage, so I wont be making any changes at this time, sorry about that.
