### ISSUE TITLE
Cant be downloaded

### ISSUE THREAD

**Issue by SVitalini** [Samueleonard/AIG-ModelMatching-For-MSFS#12]
Hey!

Thanks for your effort. Unfortunately, GDrive is the wrong hoster for such files. It denied the download because of too much traffic/size.
Would you please upload to a different, more reliable hoster? Thanks :)

**Comment by Fifcok** [comment]
If you want, I just uploaded last version

Part1:
https://modsfire.com/yh3Uld97i3JF093

Part2:
https://modsfire.com/O7X46gxSf7HGFN7

**Comment by SVitalini** [comment]
Thanks you so much :)

**Comment by SVitalini** [comment]
thats great, thank you for your effort! the OCI downloads are a pain in the
ass... so this is amazing. i have 1GB up/down internet, but the OCI is very
slow and always gets stuck... i tried for days, till i found your files :)

Am Mo., 30. Mai 2022 um 18:32 Uhr schrieb Fifcok ***@***.***>:

**Comment by Samueleonard** [comment]
thanks for uploading elsewhere, i am looking at moving to another provider, any suggestions are appreciated because i have found that gDrive is blocking people now, which is a shame but it is what it is

**Comment by Fifcok** [comment]
> 

You can use [mega.nz](https://mega.nz/), there are free 50GB

Or you can use [modsfire.com](https://modsfire.com/)(max. 3GB one file) and earn some points

**Comment by Samueleonard** [comment]
thank you, i will take a look

likely i will go to mega in the future, as im not looking to make any sort of money with this, especially because AIG is free, so it would be wrong

**Comment by Fifcok** [comment]
If someone have still problem with download from Google Drive, I just uploaded last version here:

Part1:
https://modsfire.com/B1mnJ203u9X4L0v

Part2:
https://modsfire.com/lvWdJ02x0w2P41W

**Comment by Samueleonard** [comment]
> > 
> 
> You can use [mega.nz](https://mega.nz/), there are free 50GB
> 
> Or you can use [modsfire.com](https://modsfire.com/)(max. 3GB one file) and earn some points

coming back to this
i see 2 issues with the file hosters you linked -
MEGA - i can upload fine, however free users have a max 5gb download per day, which means they cant download the pack unless they pay so that isnt an option
MODSFIRE - max 3gb, and the pack is already 5gb so that isnt an option unless i do it in 2 parts which makes further confusion with users

so if anyone has any other ideas for providers then please let me know

at current, google drive seems my best option, even with the annoying quota limits

**Comment by SVitalini** [comment]
you could use swisstransfer.ch. not really a hoster in the traditional way,
but an option...

Am Mi., 22. Juni 2022 um 22:24 Uhr schrieb Samuel Leonard <
***@***.***>:
