### ISSUE TITLE
Texture Size

### ISSUE THREAD

**Issue by SVitalini** [Samueleonard/AIG-ModelMatching-For-MSFS#13]
What texture size are you using? The full or the downscaled 2048? :)

**Comment by Samueleonard** [comment]
full

**Comment by SVitalini** [comment]
> full

any chance for the lower res option? :)

**Comment by sfkcyl** [comment]
Hello Samuel, 
First thanks for this update it is really makes our life easy. But Can you please also make it 2048. Because when you use in VATSIM. It eats 10-15 fps sometimes. 
If you able to make 2048 texture it will be really usefull. 
Thank you again for this work.

**Comment by Samueleonard** [comment]
unfortunately for me to do that would require an entire full install, which would be incredibly time consuming and the installer already is painful enough lol

sorry about that

**Comment by sfkcyl** [comment]
Can you check texture ? I have seen many of them already 2048x2048. Can you confirm ?

**Comment by Samueleonard** [comment]
im not sure then, i just leave my settings to whatever the default is

i suppose maybe you could load up the aig manager yourself and change the texture size that way? im not sure how it works though
