### ISSUE TITLE
332GE

### ISSUE THREAD

**Issue by abranpuko** [Samueleonard/AIG-ModelMatching-For-MSFS#14]
Hello, thank fo all your big work! is stunning!
I have a problem; in the MSFS, the model AIGAIM 332 GE doesnt appear. 
I have done all test but i dont know why the model does not work.
could you help me?
thank you!

**Comment by Samueleonard** [comment]
when you say it doesnt appear, do you mean it gives errors in vpilot?
there is nothing diferent with that model and any of the other models, so it is either an issue on AIGs side or your side

**Comment by abranpuko** [comment]
Oh, sorry. I use Realt traffic and PSXSeecon traffic. But now i think its solved. Thanks for your work!
