### ISSUE TITLE
Hello again! Thnaks for your updates. They are great! I would like to ask you if there is a way to make AISOUND louder. When im at airports, they pass near me but i cant hear almost anything. The sound settings on MSFS are on the top, and even the rest are less. :) thank fo your help!:)

### ISSUE THREAD

**Issue by abranpuko** [Samueleonard/AIG-ModelMatching-For-MSFS#15]

**Comment by Jannis-D** [comment]
The opposite for me. It's burning my ears away!

**Comment by abranpuko** [comment]
> 

oh, you are lucky. I dont understad why not on my MSFS. i can hear a veeery low sound when they pass near me. But nothing compared to what you are saying. Could you sent post here a "soundai".cfg to compare'?
