### ISSUE TITLE
Failed to create aircraft [...]

### ISSUE THREAD

**Issue by Fifcok** [Samueleonard/AIG-ModelMatching-For-MSFS#17]
Hello,
someone of you have problems with create aircrafts via AIG? As you can see I have problem with Lufthansa aircrafts. AIG updated 21.08.2022

![image](https://user-images.githubusercontent.com/105712834/185795393-cf2791ea-eed1-4281-9d17-04ec332d9814.png)

**Comment by Fifcok** [comment]
I have just delete all AIG and download, unzip and assign file to vPilot but still I have problem with Lufthansa

**Comment by kdries** [comment]
Have you deleted your rollingcache file and the Community\aig-aitraffic-oci-beta_CVT_ folder after the update? It's best to do this so that it is forced to look through the new models and not immediately fall back on what it has already cached.

**Comment by Fifcok** [comment]
@kdries rollingcache? You mean temp file made while unziping?

**Comment by kdries** [comment]
@Fifcok no, the ROLLINGCACHE.CCC file in your main MSFS folder which should contain the Official and Community folders as well as that file.

**Comment by Fifcok** [comment]
@kdries Ok, so I know that I must delete Community\aig-aitraffic-oci-beta_CVT_

But where is this ROLLINGCACHE.CCC file?

I have only this 3 folders in main folder of MFS2020

![image](https://user-images.githubusercontent.com/105712834/186183852-8429d3c4-590c-4ff5-88d6-5af44435c1d9.png)

Only I found this .CCC file in this weird folder, is it it?

\WpSystem\S-1-5-21-3976375018-649424627-924162844-1001\AppData\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\LocalCache

Is it safe to delete this?

Or in sim?

1. Launch Microsoft Flight Simulator
2. Go to Options > General
3. Go to Data 
4. Scroll to the bottom and go to Delete Rolling Cache File. Click on Delete
5. Confirm your choice by selecting OK

**Comment by Fifcok** [comment]
Ok I do this in sim, it helps, thanks ;)

**Comment by Fifcok** [comment]
After do everything as you said I have still this problem :(

**Comment by opr** [comment]
Also having the same issue and followed all the steps above.

```
[10:56:15] Failed to create aircraft DLH3PY using model "AIGAIM_Lufthansa Airbus A321-200neo - ACF". The model may be corrupt or missing. vPilot will try to create the aircraft with a different model.
[10:56:15] Failed to create aircraft DLH3PY using model "AIGAIM_Lufthansa Airbus A320-200neo". The model may be corrupt or missing. vPilot will try to create the aircraft with a different model.
```

**Comment by sandonov** [comment]
I am also in the same boat, and cannot find a fix so far. Tried all suggestions here.

**Comment by Samueleonard** [comment]
This is 'normal' behaviour.
AIG has some issues with the lufthansa package, some paints are missing textures so will not work.
This is not an error with your install or this package
