### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by Simms97** [Samueleonard/AIG-ModelMatching-For-MSFS#2]
Hi there, I've done all the instructions, however when starting on vpilot just bring up aload of Red Error. 

![image](https://user-images.githubusercontent.com/103338401/162593124-1b8878d0-cd5c-4a94-8ca0-59c080f0d8a4.png)

**Comment by Aviation-Adam** [comment]
do we have a fix for this? I've come across this issue, trying to reinstall it now, but having to go through the AIG manager itself to get majority of the models.

**Comment by Aviation-Adam** [comment]
Apologies, I've misunderstood the readme. I'm re-attempting the install, please ignore my reply
