### ISSUE TITLE
This is what I'm getting

### ISSUE THREAD

**Issue by Simms97** [Samueleonard/AIG-ModelMatching-For-MSFS#3]
![image](https://user-images.githubusercontent.com/103338401/162909881-760d3dc0-8b00-4b15-acdc-32df3a6a1c64.png)

I've Followed the Steps, and it's just giving me these horrible looking air planes.

**Comment by Samueleonard** [comment]
Hi, those are the default planes, not AIG.
FIrstly, have a look in the sims content manager, and see if AIG is appearing in there. If it is then you have installed it correctly and it is likely an issue with vpilot. if it is not in the content manager then you have not installed it correctly.

Im also about to update the package so use the newer version and see if that fixes your issue.
