### ISSUE TITLE
Copyright?

### ISSUE THREAD

**Issue by Kaiii3** [Samueleonard/AIG-ModelMatching-For-MSFS#4]
Just out of currisoity? Do you have the premission to upload the package here? 
If not, take the repository offline as well as the content from GoogleDrive.

**Comment by lucabrazza1** [comment]
I beg - he's literally doing everyone a favour saving them from your crappy installer.

**Comment by ko-zone** [comment]
Its almost as if you guys just want to ruin the user experience on purpose..

**Comment by iowahawkeyedave** [comment]
> Just out of currisoity? Do you have the premission to upload the package here? If not, take the repository offline as well as the content from GoogleDrive.

Do you guys intentionally want to make the experience a hassle for everyone on purpose?  Using a Github or GoogleDrive is a much faster experience.

**Comment by Kaiii3** [comment]
> > Just out of currisoity? Do you have the premission to upload the package here? If not, take the repository offline as well as the content from GoogleDrive.
> 
> Do you guys intentionally want to make the experience a hassle for everyone on purpose? Using a Github or GoogleDrive is a much faster experience.

seems you have not understand how OCI works.... AIG does only provide the Installer and the Flightplans, the other content is provided by the community and hosted on different sites. So providing a single pack is impossible because of missing premissions to upload/distribute it.
