### ISSUE TITLE
New models and missing liveries

### ISSUE THREAD

**Issue by adlouah** [Samueleonard/AIG-ModelMatching-For-MSFS#5]
Dear Samuel, 

First of all thanks much for all of your work you put into this, it's amazing! 

Secondly, how do I get my hands on additional aircraft models? Because without the correct aircraft model (e.g. DC6) any VMR file won’t be able to match the plane correctly because it misses the correct model, right? 

Also, I reckognized that Virtual Airlines are not recognized in the Sim. Is there a workaround? 

Best
adlouah

**Comment by Samueleonard** [comment]
hey,

as you said, virtual airlines are not included in aig, im not sure if they have plans to do this, you would have to ask them.

you can add multiple VMR files in vpilot, so if you find one that covers the missing models (dc6 etc), then you can use both at the same time, just make sure that mine has higher priority in vPilot :)
