### ISSUE TITLE
MD-80 and BAE-146 Missing

### ISSUE THREAD

**Issue by mfgold** [Samueleonard/AIG-ModelMatching-For-MSFS#6]
With the recent releases of the Leonardo MD-80 and JF BAE-146, the absence of both of these types is unfortunate. Are there plans to add those models + US operators of them in the future?

**Comment by Samueleonard** [comment]
unfortunately aig only has aircraft and liveries used by CURRENT operators, which means that it will have almost no 146s or md80's

this is why we need a dedicated vatsim modelmatching solution that will include all of these retro operators
