### ISSUE TITLE
using AIG with MSFS Live Traffik - Liveries did not belong to Airline

### ISSUE THREAD

**Issue by manfred2474** [Samueleonard/AIG-ModelMatching-For-MSFS#7]
Hi,
first of all thank you for this great Tool, Package or what ever it is called.
Let tell me a short story:
I fly MSFS with Real World Traffic on and love to see the correct planes: A320, B732, E195 and so on. Yesterday I was landing at my home airport in Vienna (LOWW) and then I was confused: What the matter do so much Aero Mexico Embrears in Vienne? I turned on the nameplates and: All the Aero Mexican Planes should be Austrian Airlines. Then I watched this. And as example: Nameplate was IBE, A320 - but I saw a LUFTHANSA A320.
What do I wrong that I see the correct Aircraft Type but the wrong liverie?
kind regards
Manfred

**Comment by Samueleonard** [comment]
chances are that it is just MSFS live traffic matching being weird.
as far as I know, there is nothing that I or AIG can do to make this work any better than it does

**Comment by manfred2474** [comment]
OK - thank you for you answer.
sincerly
Manfred
